#ifndef TRAVELLER_H
#define TRAVELLER_H

#include <string>

class Traveller
{
public:
    int id; // This will hold the SERIAL ID generated by PostgreSQL
    std::string name;
    std::string role;

    Traveller() {}
    Traveller(std::string name, std::string role);
};

// Subclasses cleanly map to the CHECK constraint in your database!
class Passenger : public Traveller
{
public:
    Passenger(std::string name) : Traveller(name, "Passenger") {}
};

class Astronaut : public Traveller
{
public:
    // We removed 'experience' since it isn't in your new DB schema!
    Astronaut(std::string name) : Traveller(name, "Astronaut") {}
};

class Commander : public Traveller
{
public:
    Commander(std::string name) : Traveller(name, "Commander") {}
};
void saveTravellerToDB(Traveller &t);
#endif